---
- name: Wait for nodes
  hosts: '!bastion'
  gather_facts: false
  tasks:
  - name: Wait for system to become reachable over SSH
    wait_for_connection:
      delay: 10
      timeout: 180

- name: Configure NAT
  hosts: '!bastion'
  become: true
  tasks:
  - block:

    - name: Add IP route
      shell: "ip route add default via 10.0.0.1 || true"

    - block:
      - name: Get connection UUID
        shell: nmcli -t -f UUID con show --active | head -n 1
        register: uuid
      - name: Configure DNS entry
        shell: "nmcli con mod {{ uuid.stdout }} ipv4.dns \"185.12.64.2 185.12.64.1\""
      - name: Restart NetworkManager
        shell: service NetworkManager restart
      - name: Configure NAT
        blockinfile:
          path: /etc/NetworkManager/dispatcher.d/ifup-local
          create: true
          mode: 0755
          block: |
            #!/bin/sh
            /sbin/ip route add default via 10.0.0.1
      - name: Remove package
        yum:
          name: hc-utils
          state: absent            
      when: ansible_os_family == 'RedHat'

    - block:
      - name: Get interface name
        shell: "ip route list 10.0.0.0/16 | rev | awk '{print $1}' | rev"
        register: iface
        when: ansible_os_family == 'Debian'
      - name: Configure DNS
        lineinfile:
          path: /etc/systemd/resolved.conf
          regexp: '^DNS='
          line: DNS=185.12.64.2 185.12.64.1
        register: dns
      - name: Restart service
        shell: "systemctl restart systemd-resolved.service"
        when: dns.changed
      - name: Configure NAT
        blockinfile:
          path: /etc/network/interfaces
          create: true
          block: |
            auto {{ iface.stdout }}
            iface {{ iface.stdout }} inet dhcp
                post-up ip route add default via 10.0.0.1
      - name: Install package
        apt:
          name: ifupdown
          update_cache: yes
          state: latest                    
      when: ansible_os_family == 'Debian'

    when: nat | bool
